nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmRegistries:
  'https://npm.pkg.github.com':
    npmAuthToken: { github_token }
    npmAlwaysAuth: true

npmScopes:
  k1my3ch4n:
    npmAlwaysAuth: true
    npmAuthToken: { github_token }
    npmRegistryServer: 'https://npm.pkg.github.com'
